Clarification of CNF Conformance Program, adding CNF Working Group info
cncf/cnf-conformance pull request #450
Opened 2020-10-30 00:49 UTC by taylor

- New CNF WG information added. See [WG README](cnf-wg/README.md)
- Added [WG charter](cnf-wg/charter.md)
- Clarification that CNF Conformance in main README
- New test suite specific README

2020-10-30 04:23 UTC, taylor commented
@jeffsaelens @rabi-abdel @tomkivlin

2020-10-30 11:21 UTC, tomkivlin commented on README-testsuite.md
> +- **Observability** - CNFs should externalize their internal states in a way that supports metrics, tracing, and logging.
Would "events" be useful here, or included in "logging"?

2020-10-30 11:24 UTC, tomkivlin approved these changes

2020-10-30 18:00 UTC, taylor commented
Tagging some folks @rabiabdel @CsatariGergely @collivier @fkautz  @rannyh   @ivanayov @sudeepbatra @mmiklus @rewenset @ondrej-fabry  @milanlenco  @tfherbert

2020-10-30 18:03 UTC, taylor commented
Tagging some folks @rabiabdel @CsatariGergely @collivier @fkautz  @rannyh   @ivanayov @sudeepbatra @mmiklus @rewenset @ondrej-fabry  @milanlenco  @tfherbert @TamasZsiros

2020-10-30 19:25 UTC, wavell approved these changes

2020-10-30 19:28 UTC, xmulligan commented
@bryanl

2020-10-30 19:29 UTC, xmulligan commented
@monadic

2020-10-30 19:35 UTC, jeffsaelens requested changes
overall looks good.

2020-10-30 19:35 UTC, jeffsaelens commented on README-testsuite.md
> +- **Microservice** - The CNF should be developed and delivered as a microservice.
this is a little vague. Does the CNF constitute a micro service, a suite of them? Micro service gets thrown around a lot but its a lot dicier when it involves multiple companies passing software off.

2020-10-30 19:35 UTC, jeffsaelens commented on README-testsuite.md
> +- **Statelessness** - The CNF's state should be stored in a custom resource definition or a separate database (e.g. etcd) rather than requiring local storage. The CNF should also be resilient to node
Another way to phrase this is that the state is not directly tied to the runtime (i.e. container, VM, BM etc...)

2020-10-30 19:35 UTC, jeffsaelens commented on README.md
> +The goal of the CNF Conformance Program is to provide an open source test suite to demonstrate conformance and implementation of cloud native best practices for both open and closed source Cloud Nati
just the test suite? or does the conformance umbrella provide other things?

2020-10-30 19:35 UTC, jeffsaelens commented on cnf-wg/README.md
> +The goal for the group is to create a software conformance program that any telco application implementation can use to demonstrate that they are conformant and interoperable with cloud native princi
telco application --> network application (telco is a sub-variant in this domain. we call out in the charter that large scale enterprises *who maintain their own large networks* will be a target audience as well).  We are calling them CNFs as opposed to CTF.

2020-10-30 20:25 UTC, electrocucaracha commented on README-testsuite.md
> +The CNF Conformance test suite is a tool that makes it possible to validate telco applications, aka Cloud native Network Functions (CNFs), and the underlying Telecom platforms adherence to Cloud nati
```suggestion
The CNF Conformance test suite is a tool that makes it possible to validate telco applications, aka Cloud native Network Functions (CNFs), and the underlying Telecom platforms adherence to Cloud native principles and best practices.
```

2020-10-30 20:25 UTC, electrocucaracha commented on cnf-wg/README.md
> +The CNF WG operates under the aegis of CNCF. The charter of the working group is to define the process around certifying the cloud nativeness of telco applications,  aka CNFs. We collaborate with the
```suggestion
The CNF WG operates under the aegis of CNCF. The charter of the working group is to define the process around certifying the cloud nativeness of telco applications,  aka CNFs. We collaborate with the [CNF Conformance test suite project](README-testsuite.md) who work on the mechanics of the conformance tests.
```

2020-10-30 21:42 UTC, taylor commented on README.md
> +The goal of the CNF Conformance Program is to provide an open source test suite to demonstrate conformance and implementation of cloud native best practices for both open and closed source Cloud Nati
ATM the Program consists of the WG and the test suite project.

- The WG will produce requirements and best practice information for CNFs. It will also create the process for certifying.
- The Test suite project will create tests and maintain the testing software.

No other things as of yet.

2020-10-30 21:46 UTC, taylor commented on cnf-wg/README.md
> +The goal for the group is to create a software conformance program that any telco application implementation can use to demonstrate that they are conformant and interoperable with cloud native princi
I like that terminology. I think there will need to be adjustments in the rest of the doc to talk about telco as a subset of the network domain.

2020-10-30 21:49 UTC, taylor commented on README-testsuite.md
> +- **Microservice** - The CNF should be developed and delivered as a microservice.
@jeffsaelens these are moved over as-is from the original README about the test suite categories.  I'd prefer move the discussion to a followup specific to updating the test suite docs rather than in this PR which is focused on the WG. That said I think this could be addressed in the WG as defining what a CNF is with in scope, so exploring where the microservice lives is relevant :)

2020-10-30 23:27 UTC, jeffsaelens commented on README.md
> +The goal of the CNF Conformance Program is to provide an open source test suite to demonstrate conformance and implementation of cloud native best practices for both open and closed source Cloud Nati
only reason I asked as its phrased as the CNF Conformance Program as opposed to specifically referencing the Test Suite. Just confused me.

2020-10-31 13:50 UTC, dabernie commented on README.md
> +The goal of the CNF Conformance Program is to provide an open source test suite to demonstrate conformance and implementation of cloud native best practices for both open and closed source Cloud Nati
I'm good with that definition

2020-10-31 14:31 UTC, jeffsaelens commented on README-testsuite.md
> +
"underlying Telecom platforms" --> networking infrastructure and telecommunications workloads?

2020-11-01 14:42 UTC, dabernie commented on cnf-wg/charter.md
> +- Cloud native conformance test requirements for Telcom platforms (which run CNFs)
Where does the Telcom acronym comes from ? 1st time being used ... should be "Telco platforms"

2020-11-01 14:42 UTC, dabernie commented on cnf-wg/charter.md
> +
what about k8s-sig-networking, k8s-sig-multitenancy, cncf sig service mesh, k8snetworkplumbing ?

2020-11-02 09:43 UTC, xmulligan commented on cnf-wg/charter.md
> +- Cloud native conformance test requirements for Telcom platforms (which run CNFs)
```suggestion
- Cloud native conformance test requirements for Telco platforms (which run CNFs)
```

2020-11-02 10:29 UTC, rabi-abdel reviewed
Really great content. looking forward to participate in it.

2020-11-02 10:29 UTC, rabi-abdel commented on cnf-wg/charter.md
> +- Portable - Cloud native workloads run everywhere -- public cloud, private cloud, bare metal, laptop -- with consistent behavior so that they are portable throughout the ecosystem as well as between
```suggestion
- Portable - Cloud native workloads run everywhere -- public cloud, private cloud, bare metal, laptop -- with consistent functional behavior so that they are portable throughout the ecosystem as well as between development and production environments.
```

2020-11-02 10:29 UTC, rabi-abdel commented on cnf-wg/charter.md
> +- Automatable. Cloud native workloads should aim to dramatically reduce the burden of manual operations. They support both declarative control by specifying users’ desired intent via an API, as well
```suggestion
- Automatable. Cloud native workloads should aim to help dramatically reduce the burden of manual operations. They support both declarative control by specifying users’ desired intent via an API, as well as imperative control to support higher-level orchestration and automation. The declarative approach is key to the ecosystem’s self-healing and autonomic capabilities.
```

2020-11-02 10:29 UTC, rabi-abdel commented on cnf-wg/charter.md
> +- Process around certifying CNF conformance
```suggestion
- Process around certifying CNFs.
```

2020-11-02 10:29 UTC, rabi-abdel commented on cnf-wg/charter.md
> +- Feedback into other related groups and specifications to improve CNF use cases (e.g. SIG App Delivery, SIG Networking, CNI)
```suggestion
- Feedback into other related groups and specification bodies to improve CNF use cases (e.g. SIG App Delivery, SIG Networking, CNI)
```

2020-11-02 10:29 UTC, rabi-abdel commented on cnf-wg/charter.md
> +- Cloud native conformance test requirements for Telco platforms (which run CNFs)
```suggestion
- Cloud native conformance requirements for Telco platforms (which run CNFs)
```

2020-11-02 10:30 UTC, rabi-abdel approved these changes

2020-11-02 11:46 UTC, nickolaev commented on README.md
> +Interoperability: Workloads can be ported across various cloud native infrastructures. This standardization is a key advantage of open source software, and allows you to avoid vendor lock-in.
There was a question on today's TUG call in the lines of "can my CNF depend on an SDN infrastructure for e.g. SFC?". Apparently, this is an important need for some of the solutions that do exist, which essentially opens the following questions:
 - how "smart/programmable" is the cloud-native infrastructure expected to be?
 - shall we consider the "smartness" being an application that runs on top of the "dumb" infrastructure?
 - if I depend on that "smartness" do I bring it with my app, or it's better to just drop and rethink my app

2020-11-02 11:51 UTC, nickolaev commented on cnf-wg/charter.md
> +- Extensible. Cloud native workloads should integrate into your environment and add the additional capabilities you need.
As is typical in this domain - do HW accelerators fit in here? I mean, can my FPGA custom Firmware NIC be exposed in a sane, non-binding way, so that my app can leverage it if it's there but can still do low-performance functions if it's not?

2020-11-02 11:52 UTC, nickolaev approved these changes
I love the initiative! Looking forward to the kick-off meeting!

2020-11-02 15:43 UTC, taylor commented on README.md
> +The goal of the CNF Conformance Program is to provide an open source test suite to demonstrate conformance and implementation of cloud native best practices for both open and closed source Cloud Nati
@jeffsaelens the top level REAMDE is for the umbrella program which includes a test suite project and the new working group. In the future we may split things into different repos.

2020-11-02 16:56 UTC, taylor commented on cnf-wg/charter.md
> +
@dabernie, sure. Maybe it should be worded to give a few examples vs pointing out any that may be worked with more than others. There is a lot of overlap.

2020-11-02 17:10 UTC, taylor commented on cnf-wg/charter.md
> +- Process around certifying CNF conformance
Defining what a CNF is in scope. That is possibly different from certification. For the certifying I think we are trying to say how something adheres to cloud native best practices + principles.  

Do we want something more focused, such as:

> Process around certifying CNFs adherence to cloud native principles

if not then I like the suggestion from @rabi-abdel which is more general.

@caniszczyk @xmulligan

2020-11-02 18:54 UTC, taylor commented on README.md
> +Interoperability: Workloads can be ported across various cloud native infrastructures. This standardization is a key advantage of open source software, and allows you to avoid vendor lock-in.
IMO, the application should degrade gracefully.  Design to expect failure. Ideally the app can provide a degraded service even if piece of hardware is not available.

A new workload can describe what it wants and ideally orchestrator will try to match a node which has those resources. This would be similar to asking for a system with a GPU for processing or something else.

2020-11-02 22:01 UTC, Ananth-kr commented
Thanks for starting this thread and for the great content.
I think one of the best practices that can go under resources is that :

Userplane(data plane)  CNF pods should use Guaranteed QOS class(Resource Request and Limit should be the same).

Though this is not a hard and fast rule that this should be followed.If this is not followed this particular CNF can cause performance issues to other CNFs because of resource contention.

**Some Background:**
 [ https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/ ]
Its a common practice in Kubernetes to create pods with Burstable QOS class but this doesn't work for CNFs where latency can not be tolerated.

For eg: 
If there is a pod (one of the container components in NF) running in Burstable QOS class (or non gqos) and if another Burstable pod gets scheduled on to the same worker node then both pods will share the same set of CPUs causing latency and other performance issues.

 I think depending on the Kubernetes releases this could affect a Guaranteed QoS class pod as well and can be disastrous for both CNFs. (At least on K8s 1.18+ Kubelet is repinning burstable pod from guaranteed,but still it's not ideal to use non guaranteed QoS class for data plane CNFs) 

So i think even if a CNF is following all the best practices mentioned here if it doesn't follow guaranteed QoS class it could not deliver the required performance.

**Some assumptions:**
Worker nodes are tuned for latency-sensitive workloads 
No 1:1 mapping between CNF and worker nodes 
Telco cloud is generic for hosting multiple CNF

If you think that this is important and not yet considered then I can request a PR if it's okay.

2020-11-03 10:12 UTC, tomkivlin approved these changes

2020-11-03 10:48 UTC, CsatariGergely requested changes

2020-11-03 10:48 UTC, CsatariGergely commented on README-testsuite.md
> +
In stead of "underlying Telecom platforms" I would use "underlying cloud infrastructures". Telecom platforms are platforms to provide telecom services.

2020-11-03 10:48 UTC, CsatariGergely commented on README-testsuite.md
> +- **Statelessness** - The CNF's state should be stored in a custom resource definition or a separate database (e.g. etcd) rather than requiring local storage. The CNF should also be resilient to node
I agree, and by saying this we do not try to architect the internals of the CNF-s.

2020-11-03 10:48 UTC, CsatariGergely commented on README-testsuite.md
> +- **Security** - CNF containers should be isolated from one another and the host.
What level of isolation is required here? I do not think that we should mandate the usage of VMM based runtimes all the time. This should depend on the use case.

2020-11-03 10:48 UTC, CsatariGergely commented on README-testsuite.md
> +- **Microservice** - The CNF should be developed and delivered as a microservice.
I agree, that this needs some more discussion. Can we indicate somehow, that this is not in agreement yet?

2020-11-03 10:48 UTC, CsatariGergely commented on README-testsuite.md
> +- **Scalability** - CNFs should support horizontal scaling (across multiple machines) and vertical scaling (between sizes of machines).
Scaling is usually defined in relation to self (horizontal scaling -> scaling by multiplication, vertical scaling -> scaling by changing the size of the thing) and not related to "machines". Capability to scale across multiple and between sizes of machines requires horizontal scaling from the service. Assuming that "machine" is the host here.

2020-11-03 10:48 UTC, CsatariGergely commented on README-testsuite.md
> +- **Installable and Upgradeable** - CNFs should use standard, in-band deployment tools such as Helm (version 3) charts.
What is in-band here?

2020-11-03 10:48 UTC, CsatariGergely commented on README-testsuite.md
> +- **Hardware Resources and Scheduling** - The CNF container should access all hardware and schedule to specific worker nodes by using a device plugin.
Maybe ... should be able to access all type of hardware and be scheduled to specific worker nodes by using device plugins if needed. 

but still I think to consume accelerators, GPU-s, FPGA-s or similar things specific drivers are needed independently from the usage of device plugins. (There are discussions about HW acceleration abstraction in CNTT and in O-RAN WG6, but there are no implementaitons yet)

2020-11-03 10:48 UTC, CsatariGergely commented on README-testsuite.md
> +
## Governance is missing

Who are the current leaders and how people can become leaders.

2020-11-03 10:48 UTC, CsatariGergely commented on README.md
> +With such a wide array of applications being developed today, workload conformance tests help ensure that developers can follow cloud native best practices when building greenfield applications and/o
I think the last sentence is not needed.

2020-11-03 10:48 UTC, CsatariGergely commented on cnf-wg/charter.md
> +The goal of the Cloud Native Network Functions Working Group (CNF WG)  is to aid companies such as communications service providers and large scale enterprises, running internal telecommunications-li
```suggestion
The goal of the Cloud Native Network Functions Working Group (CNF WG)  is to aid companies such as telecom vendors, communications service providers and large scale enterprises, running internal telecommunications-like infrastructure, to better understand what cloud native means for telecommunications workloads and help build consensus around industry adoption of cloud native technologies (per CNCF TUG).
```

I (:)) suprisingly think that this is most important for the ones who are building the CNF-s, the telecom vendors. 

I think we should have a TUG whitepaper first before we refer to it. In my opinion CNCF TUG never finished agreeing in one WP. We have different bits and pieces written in different pieces by different members of CNCF TUG, but I would not call any of them the TUG WP.

2020-11-03 10:48 UTC, CsatariGergely commented on cnf-wg/charter.md
> +The goal for the group is to create a software conformance program that any application or network function implementation can use to demonstrate that they are conformant and interoperable with cloud
I think there are some areas where we would need to have some agreement "on-top" of cloud native best practices, like how to name Kubernetes resources or what kind of API we use to manage CNF-s on top that it should be a CRD (what is not more specific than "it should be an API") and similar things. Shouldn't we add these to the scope of the CNF WG or are these in the scope of the TUG? What others think?

2020-11-03 10:48 UTC, CsatariGergely commented on cnf-wg/charter.md
> +- Definition of Cloud native Network Function (CNF)
Wasn't this already defined by the CNCF TUG?

2020-11-03 10:48 UTC, CsatariGergely commented on cnf-wg/charter.md
> +- Feedback into other related groups and specification bodies to improve CNF use cases (e.g. SIG App Delivery, SIG Networking, CNI)
How about downstream communities, like CNTT?

2020-11-03 10:48 UTC, CsatariGergely commented on cnf-wg/charter.md
> +- Cloud native conformance requirements for Telco platforms (which run CNFs)
This is in the scope of CNTT RA2, therefore we should not have it here.

2020-11-03 10:48 UTC, CsatariGergely commented on cnf-wg/charter.md
> +- CNTT R2 - is focused on Kubernetes-based platforms and basic interoperability between platform and workloads. CNTT R2 has not determined if workload cloud native requirements are in scope for CNTT
I think CNF requirements related to the infrastructure are in scope for CNTT RA2. @tomkivlin what do you think?

2020-11-03 11:16 UTC, tomkivlin commented on cnf-wg/charter.md
> +- CNTT R2 - is focused on Kubernetes-based platforms and basic interoperability between platform and workloads. CNTT R2 has not determined if workload cloud native requirements are in scope for CNTT
@CsatariGergely I agree, but I think that's what "basic interoperability between platform and workloads" covers?

2020-11-03 15:38 UTC, taylor commented on README-testsuite.md
> +
@CsatariGergely these comments are good for discussion in the test suite initiative itself. The new WG is separate from the test suite group, which is the point of this PR. 

The README-testsuite.md was created using existing content for the test suite that was moved from the README.md.  It should have been moved in a different PR.

2020-11-03 19:19 UTC, taylor commented on README-testsuite.md
> +
The test suite project will have independent governance from the new working group. We have a contributing guide for the test suite itself. Further governance will be aligned with the TOCs guidelines so that the project can request to be a sandbox project in the future.

2020-11-03 19:19 UTC, taylor commented on cnf-wg/charter.md
> +The goal of the Cloud Native Network Functions Working Group (CNF WG)  is to aid companies such as communications service providers and large scale enterprises, running internal telecommunications-li
That paragraph is referring to what the TUG white-paper did cover which was the intent.  

The TUG can create new white-papers which may have a broader scope or whatever it deems useful.

This WG will be defining what it means for a telco/network application to adhere to cloud native best practices and principles as well as the process for certification.

2020-11-03 19:19 UTC, taylor commented on cnf-wg/charter.md
> +The goal for the group is to create a software conformance program that any application or network function implementation can use to demonstrate that they are conformant and interoperable with cloud
The request was to start with a narrower scope and only added when required. I expect that areas that are touched will at least be in the discussion for context even if they are not in scope for defining requirements.

2020-11-03 19:19 UTC, taylor commented on cnf-wg/charter.md
> +- Definition of Cloud native Network Function (CNF)
It will be reviewed and maintained in the CNF WG as a basis for the conformance definitions TBD by the broader group including leaders from other CNCF+K8s SIGs and WGs.

2020-11-03 19:19 UTC, taylor commented on cnf-wg/charter.md
> +- Feedback into other related groups and specification bodies to improve CNF use cases (e.g. SIG App Delivery, SIG Networking, CNI)
Sure. ORAN, TIP, and others as well.

Note the e.g. indicating just a few mentioned, not all.

2020-11-03 19:19 UTC, taylor commented on cnf-wg/charter.md
> +- CNTT R2 - is focused on Kubernetes-based platforms and basic interoperability between platform and workloads. CNTT R2 has not determined if workload cloud native requirements are in scope for CNTT
CNTT RA2 is creating an opinionated K8s telco distro.

If it wants to have workload requirements beyond basic interoperability it can choose to include the CNF Conformance requirements in addition to what ever other requirements it wishes to add.

2020-11-03 19:21 UTC, taylor commented on cnf-wg/charter.md
> +- Cloud native conformance requirements for Telco platforms (which run CNFs)
ATM it is out of scope for the WG. In the future it may decide to extend the scope, if a new CNCF group is not formed, which focuses on the layers under the telco applications. This would be focused on cloud native best practices/principles for infra/platform layers -- which is in scope for CNCF.

2020-11-03 19:23 UTC, taylor commented on cnf-wg/charter.md
> +
@dabernie updated wording.

> A few of the groups with potential interactions/collaboration are:

2020-11-04 14:54 UTC, CsatariGergely commented on cnf-wg/charter.md
> +- CNTT R2 - is focused on Kubernetes-based platforms and basic interoperability between platform and workloads. CNTT R2 has not determined if workload cloud native requirements are in scope for CNTT
@tomkivlin yes, that is true, I'm more worried about the "CNTT R2 has not determined if workload cloud native requirements are in scope for CNTT R2" part. We have the (still empty) [Chapter 4.9](https://cntt.readthedocs.io/en/latest/ref_arch/kubernetes/chapters/chapter04.html#4.9) in RA2.

2020-11-04 22:41 UTC, taylor commented on cnf-wg/charter.md
> +- Process around certifying CNF conformance
@rabi-abdel how about 

> Process around certifying the cloud native conformance of CNFs

which is the intent of the original wording. Maybe the intent is given based on the program being about cloud native?

2020-11-05 19:42 UTC, xmulligan commented on README-testsuite.md
> +
this discussion can be continued in #460

2020-11-05 19:42 UTC, xmulligan commented on README-testsuite.md
> +- **Statelessness** - The CNF's state should be stored in a custom resource definition or a separate database (e.g. etcd) rather than requiring local storage. The CNF should also be resilient to node
see #460 for further discussion

2020-11-05 19:43 UTC, xmulligan commented on README-testsuite.md
> +- **Security** - CNF containers should be isolated from one another and the host.
see #460 for further discussion

2020-11-05 19:43 UTC, xmulligan commented on README-testsuite.md
> +- **Microservice** - The CNF should be developed and delivered as a microservice.
see #460 for further discussion

2020-11-05 19:43 UTC, xmulligan commented on README-testsuite.md
> +- **Installable and Upgradeable** - CNFs should use standard, in-band deployment tools such as Helm (version 3) charts.
see #460 for further discussion

2020-11-05 19:43 UTC, xmulligan commented on README-testsuite.md
> +- **Hardware Resources and Scheduling** - The CNF container should access all hardware and schedule to specific worker nodes by using a device plugin.
see #460 for further discussion

2020-11-05 19:44 UTC, xmulligan commented on README.md
> +With such a wide array of applications being developed today, workload conformance tests help ensure that developers can follow cloud native best practices when building greenfield applications and/o
which sentence are you referring to?

2020-11-05 19:50 UTC, xmulligan commented on cnf-wg/charter.md
> +- Definition of Cloud native Network Function (CNF)
Yes, we are seeking to formalize the structure and make it more of a living document so as the state of the art in cloud native progresses so does the definition

2020-11-05 19:52 UTC, xmulligan commented
@CsatariGergely are any of the above comments blockers for you to approve this PR?

2020-11-05 21:02 UTC, rannyh commented on cnf-wg/charter.md
> +
What about interaction with non-CNCF projects, E.g. ONAP? There might be a benefit in some sort of alignment (or at least mutual awareness) with ONAP. BTW- I volunteer to serve as aa liaison ;-)

2020-11-05 21:13 UTC, rannyh commented on cnf-wg/charter.md
> +
What about interaction with non-CNCF projects, E.g. ONAP? There might be a benefit in some sort of alignment (or at least mutual awareness) with ONAP. BTW- I volunteer to serve as aa liaison ;-)

2020-11-05 22:29 UTC, taylor commented on cnf-wg/charter.md
> +
@rannyh, I expect there will be interactions with many non-CNCF orgs and projects. Ideally ONAP folks will participate in the CNF Working Group to provide input. 

Beyond that there are several ways to collaborate with testing itself including ONAP running tests from the test suite as part of onboarding CNFs as well as testing ONAP components themselves.

2020-11-05 22:45 UTC, taylor commented on cnf-wg/README.md
> +The goal for the group is to create a software conformance program that any telco application implementation can use to demonstrate that they are conformant and interoperable with cloud native princi
```suggestion
The goal for the group is to create a software conformance program that any network application implementation can use to demonstrate that it is conformant and interoperable with cloud native principles.
```

2020-11-05 22:50 UTC, taylor commented on README-testsuite.md
> +- **Scalability** - CNFs should support horizontal scaling (across multiple machines) and vertical scaling (between sizes of machines).
@CsatariGergely I would like to address changes to the test suite docs in a new PR or issue. This new README-testsuite.md has content moved verbatim from the original README.

2020-11-05 22:56 UTC, taylor commented on cnf-wg/charter.md
> +- Extensible. Cloud native workloads should integrate into your environment and add the additional capabilities you need.
In scope for discussion, right now, I presume would be that the app should be able to declaratively ask for some mechanism for using the FPGA custom Firmware NIC. 

That would imply that someone, even if it's not in this WG, should be figuring out how to expose access to those resources for that cloud native application to utilize.

2020-11-06 00:52 UTC, rannyh approved these changes
Looks like a good start

2020-11-06 05:51 UTC, dabernie commented on README.md
> +Interoperability: Workloads can be ported across various cloud native infrastructures. This standardization is a key advantage of open source software, and allows you to avoid vendor lock-in.
In the case of SFC which is a global construct, a CNF is but one component in the service graph. Question would then be wether the SFC control (understanding relations between CNFs) should it be part of the Conformance scenario or independent.

2020-11-06 05:55 UTC, dabernie commented on README.md
> +Running applications in a cloud native manner will allow you more fully utilize the advantages of cloud native infrastructure. The CNF Conformance program enables interoperability of Cloud native Net
Should it say "Running applications in a cloud native manner will allow for fully benefit from the advantages ..."

2020-11-06 06:01 UTC, dabernie commented on cnf-wg/charter.md
> +- Extensible. Cloud native workloads should integrate into your environment and add the additional capabilities you need.
It depends, infrastructure might provide the API to have access to the FPGA but a CNF would need to add the appropriate IP or runtime code associated with itself. Exemple node has an FPGA attached, it cannot load the FW microcode unless it knows there will be a FW CNF instantiated on that perticular node

2020-11-06 06:06 UTC, dabernie commented on cnf-wg/charter.md
> +- CNTT R2 - is focused on Kubernetes-based platforms and basic interoperability between platform and workloads. CNTT R2 has not determined if workload cloud native requirements are in scope for CNTT
CNF requirements should remain outside of CNTT RA2 scope although it can relate and promote them. CNF conformance and requirements need to be also applicable to non CNTT-RA2 compliant platforms.

2020-11-06 06:08 UTC, dabernie commented on cnf-wg/charter.md
> +
Does it only target these k8s-sigs ? should it not include some like multi-tenancy, networking ?

2020-11-06 06:08 UTC, dabernie approved these changes

2020-11-06 07:27 UTC, nickolaev approved these changes
I see lots of excitement here. Let's make this happen.

2020-11-06 12:22 UTC, rabi-abdel approved these changes
All looks good to me.

2020-11-06 16:57 UTC, taylor commented on cnf-wg/charter.md
> +
@dabernie this is just an example set of the SIGs and groups we expect to collaborate with not a full list.

2020-11-06 19:04 UTC, taylor commented on README.md
> +Running applications in a cloud native manner will allow you more fully utilize the advantages of cloud native infrastructure. The CNF Conformance program enables interoperability of Cloud native Net
```suggestion
Implementing and running applications in a cloud native manner will enable you to more fully benefit from the advantages cloud native infrastructure.
```

2020-11-06 19:16 UTC, dabernie commented on README.md
> +Running applications in a cloud native manner will allow you more fully utilize the advantages of cloud native infrastructure. The CNF Conformance program enables interoperability of Cloud native Net
👍

2020-11-06 19:31 UTC, rannyh commented on README.md
> +Running applications in a cloud native manner will allow you more fully utilize the advantages of cloud native infrastructure. The CNF Conformance program enables interoperability of Cloud native Net
👍

2020-11-06 21:41 UTC, merged

2020-11-06 21:43 UTC, taylor commented
This is the first iteration of the WG documents. 

There will be further updates in these docs as well as new docs created by the WG. Please join the upcoming kickoff meeting at Kubecon https://sched.co/fRkx.

2020-11-09 13:29 UTC, xmulligan commented
@rannyh @nickolaev @Ananth-vr and everyone else thanks for helping out on this first PR! We haven't met yet, but I would be happy to chat with you about the initiative and get to know you more. Feel free to book a time with me https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2020-11