#44 Update documentation for platform hardware and scheduling
cncf/cnf-conformance pull request #467
Opened 2020-11-10 17:35 UTC by wavell

# #44 Update documentation

## Description
#44 Update documentation

## Issues:
Refs: #NNN

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2020-11-10 17:43 UTC, agentpoyo approved these changes
LGTM :+1:

2020-11-10 22:03 UTC, taylor requested changes

2020-11-10 22:03 UTC, taylor commented on USAGE.md
> +./cnf-conformance  platform:hardware_and_scheduling poc
It seems this should not have poc listed if it's not in the POC section (below)

```suggestion
./cnf-conformance  platform:hardware_and_scheduling
```

2020-11-12 16:00 UTC, taylor approved these changes

2020-11-12 16:05 UTC, merged