add rolling downgrade and version change tasks
cncf/cnf-conformance pull request #469
Opened 2020-11-12 05:32 UTC by williscool

may rename.

still working on rollback

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-to-a-previous-revision

# CNF Conformance PR Template

## Description
(name of issue/change)

## Issues:
Refs: #82 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2020-11-30 23:06 UTC, wavell requested changes

2020-11-30 23:06 UTC, wavell commented on example-cnfs/coredns/cnf-conformance.yml
> -rolling_update_tag: 1.6.7
These should go under container_names now

2020-11-30 23:06 UTC, wavell commented on src/tasks/configuration_lifecycle.cr
> +def get_helm_chart_values(sam_args, release_name)
We should use the k8s api now instead of the helm chat

2020-11-30 23:06 UTC, wavell commented on src/tasks/configuration_lifecycle.cr
> +    if config.has_key? "rollback_from_tag"
We should get these from the container_names config now

2020-11-30 23:06 UTC, wavell commented on src/tasks/configuration_lifecycle.cr
> +    helm_chart_values = get_helm_chart_values(args, release_name)
we should use the k8s api instead of helm

2020-11-30 23:06 UTC, wavell commented on src/tasks/utils/types/cnf_conformance_yml_type.cr
> +  property rolling_downgrade_tag : String?
These should go under container names

2020-12-04 23:08 UTC, agentpoyo approved these changes
LGTM :+1:

2020-12-07 18:07 UTC, wavell approved these changes

2020-12-07 19:56 UTC, nupejosh approved these changes
👍

2020-12-07 20:24 UTC, merged