Updated test-cat and usage to include rollback (rolling_downgrade)
cncf/cnf-conformance pull request #523
Opened 2020-12-10 20:14 UTC by agentpoyo

# CNF Conformance PR Template

### Description
Missing doc updates for #82

--
### Documentation is updated:
- [x] On https://github.com/cncf/cnf-conformance/blob/master/USAGE.md#installable-and-upgradeable-tests, I can see:
     - [x] the `rolling_downgrade`  test added to the USAGE.md and marked with a checkmark (or POC, depending on what is completed in this issue) 
     - [x] a new sentence describing what the `rolling_downgrade` test does
- [x] On https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md#installable-and-upgradeable-tests, I can see a new sentence about `rolling_deployment_downgrade` 

## Issues:
Refs: #82 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2020-12-11 12:55 UTC, agentpoyo commented on TEST-CATEGORIES.md
> +*  Testing if the CNF can perform a rolling_downgrade and rollback (i.e. [kubectl_rollout_undo](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-to-a-previous-revisi
I can't decide if it's better to create separate lines for rolling_downgrade and rollback or keep on the same line, since they're sort of in the same in concept of backing out changes (that's if one upgrades and then later decides they need to downgrade).

2020-12-17 00:24 UTC, williscool commented on TEST-CATEGORIES.md
> +*  Testing if the CNF can perform a rolling_downgrade and rollback (i.e. [kubectl_rollout_undo](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-to-a-previous-revisi
lgtm rollback should def be on a seperate line since its implementation is different.

but `rolling_downgrade` is an alias of `rolling_update` not rollback so that might be confusing

2020-12-17 00:25 UTC, williscool approved these changes
approved pending comment changes

2020-12-22 16:41 UTC, taylor requested changes
@agentpoyo the rolling downgrade is the one confusing item. Maybe the rolling update should communicate that it updates forward and backwards in versions instead. For now removing the rolling downgrade sounds like a good plan.

Everything else lgtm

2020-12-22 17:53 UTC, taylor approved these changes
lgtm

2020-12-22 17:53 UTC, merged