add seperate file for installing from source
cncf/cnf-conformance pull request #534
Opened 2020-12-16 18:19 UTC by williscool

# CNF Conformance PR Template

## Description
(name of issue/change)

## Issues:
Refs:  #526

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2020-12-16 22:51 UTC, williscool commented on INSTALL.md
> +#### Requirements for source installation
I think we should remove all info related to source install from `INSTALL.md` and only have it in `SOURCE_INSTALL..md`

will copy this over myself

2020-12-16 22:51 UTC, williscool commented on INSTALL.md
> +#### Source Install
re: removing all info related to source install from INSTALL.md and only have it in SOURCE_INSTALL..md

I think the only thing INSTALL.md should have in it related to the source install is a link to the other md

2020-12-16 23:08 UTC, taylor requested changes

2020-12-16 23:08 UTC, taylor commented on INSTALL.md
> +If you want to run all tests, do the following (this is assuming you your `cnf_setup` ran without errors in the [configuration](#Configuration) steps:)
Some where before this we should tell the user to run the cnf_setup command with their cnf-conformance.yml (example or bring your own cnf)

2020-12-16 23:08 UTC, taylor commented on INSTALL.md
Something should be said about the final results.

2020-12-16 23:08 UTC, taylor commented on INSTALL.md
> +For complete usage, see the [USAGE.md](USAGE.md) doc.
Adding a category example and individual test example could be useful here but maybe its better to get them to the usage doc sooner.

2020-12-16 23:08 UTC, taylor commented on SOURCE_INSTALL.md
> +```
I suggest moving this up to the other usage section and making it a collapsed item for more examples

2020-12-16 23:10 UTC, agentpoyo commented on INSTALL.md
>  curl https://raw.githubusercontent.com/cncf/cnf-conformance/master/curl_install.sh | bash
I kept some of the original terminology intact but you're likely correct.

I can collapse the non-preferred method and name it "alternate method"

2020-12-16 23:12 UTC, agentpoyo commented on INSTALL.md
> -- Move the downloaded binary to somewhere in your executable PATH (eg. `sudo cp cnf-conformance /usr/local/bin/cnf-conformance`)
Those lines were removed..

2020-12-16 23:13 UTC, agentpoyo commented on INSTALL.md
> +#### Testing Your Own CNF
I had a hard time with this one myself..  and left it at Testing.

I like "Configuring" though..

2020-12-16 23:15 UTC, agentpoyo commented on INSTALL.md
> +If you want to run all tests, do the following (this is assuming you your `cnf_setup` ran without errors in the [configuration](#Configuration) steps:)
Yeah, I'm hoping they're following the INSTALL step by step. Trying to not be so redundant.

2020-12-16 23:16 UTC, agentpoyo commented on INSTALL.md
Yeah, perhaps it should get it's own MD file? This starts diving outside of the actual `INSTALL` of the suite..

2020-12-16 23:16 UTC, agentpoyo commented on INSTALL.md
> +For complete usage, see the [USAGE.md](USAGE.md) doc.
Yes, we can move the USAGE link at the beginning perhaps?

2020-12-16 23:17 UTC, taylor commented on INSTALL.md
> +#### Source Install
How about a link and a collapsed area with the brief install info?  For example:
```
See the SOURCE-INSTALL document for information on building and using the test suite from source.

▶️ Click here for brief source build details

Follow these steps to checkout the source from github and compile a cnf-conformance binary:

git clone git@github.com:cncf/cnf-conformance.git
cd cnf-conformance/
shards install
crystal build src/cnf-conformance.cr
This should build a cnf-conformance binary in the root directory of the git repo clone.

```

2020-12-16 23:24 UTC, taylor commented on INSTALL.md
> -- Move the downloaded binary to somewhere in your executable PATH (eg. `sudo cp cnf-conformance /usr/local/bin/cnf-conformance`)
Yes. I'm suggesting they be added back as an alternative method of using a published binary release.

What does an end user do that wants to use a specific release and not the latest release?

2020-12-16 23:26 UTC, taylor commented on INSTALL.md
> +If you want to run all tests, do the following (this is assuming you your `cnf_setup` ran without errors in the [configuration](#Configuration) steps:)
@agentpoyo the docs never tell the user to run cnf_setup when they bring their own cnf.

2020-12-16 23:33 UTC, taylor commented on INSTALL.md
> +cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml
Move this to after the "Testing Your Own CNF" section as it's applicable to both.

2020-12-16 23:34 UTC, taylor commented on INSTALL.md
Yes... it could go from and install guide to a section of usage for results.

A quick how to see results does not seem bad here though.

2020-12-16 23:37 UTC, taylor commented on INSTALL.md
> +#### Testing Your Own CNF
I guess its fine as-is.  I think the example section should look the same though. See other comment

2020-12-16 23:38 UTC, taylor commented on INSTALL.md
> +#### Example CNF
```suggestion
#### Testing an Example CNF
```

to match current "Testing Your Own CNF"

2020-12-17 21:50 UTC, agentpoyo commented on INSTALL.md
> -- Move the downloaded binary to somewhere in your executable PATH (eg. `sudo cp cnf-conformance /usr/local/bin/cnf-conformance`)
If we prefer the curl method that adds to path, this would ideally be under a optional drop down. I thought about doing "3 methods" that kept these types of steps in them but figured it's just adding to the overall length of the INSTALL.md doc

I think most would know how to pull down manually and chmod+x the binary if they prefer such method.

2020-12-17 22:10 UTC, agentpoyo commented on INSTALL.md
> +If you want to run all tests, do the following (this is assuming you your `cnf_setup` ran without errors in the [configuration](#Configuration) steps:)
I planned to add more of the Bring your own CNF in the CNF-CONFORMANCE-YML-USAGE doc that expands on more of the bringing/making your own cnf-conformance.yml file.

2020-12-17 22:23 UTC, agentpoyo commented on INSTALL.md
> +For complete usage, see the [USAGE.md](USAGE.md) doc.
Moved this up before the example commands.

2020-12-17 22:27 UTC, agentpoyo commented on INSTALL.md
Less is more..  Points gets it's own POINTS.md file for explaining results.

2020-12-17 22:45 UTC, agentpoyo commented on INSTALL.md
> +#### Requirements for source installation
See below, making it collapsible.

2020-12-17 22:47 UTC, agentpoyo commented on INSTALL.md
> -- Move the downloaded binary to somewhere in your executable PATH (eg. `sudo cp cnf-conformance /usr/local/bin/cnf-conformance`)
I added the manual install with chmod +x but it will be in the alternate collapsible steps (optional) since it's not our preferred method.

2020-12-18 00:15 UTC, taylor requested changes
The only item is the cnf_setup location and the source cnf_setup command.  Everything else is good to go imo.

2020-12-18 00:15 UTC, taylor commented on INSTALL.md
> +cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml
This, `cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml` should be moved after both "using an example cnf" and "bring your own cnf" as it is applicable to both listed for the latter (meaning it would be missed by folks not using the example).

<img width="705" alt="Screen Shot 2020-12-17 at 6 09 37 PM" src="https://user-images.githubusercontent.com/26697/102558708-ac4c8c00-4093-11eb-9318-e6d67afb98dc.png">



Also I'm still seeing the source option as can be seen in the image with I choose "Display the rich diff"

![image](https://user-images.githubusercontent.com/26697/102558626-76a7a300-4093-11eb-9dec-0cc0bb5027ba.png)

2020-12-18 00:16 UTC, taylor commented on SOURCE_INSTALL.md
> +```
If we want a first rev of the source guide then we can skip more changes there.  Getting the new INSTALL.md out is the most important issue IMO.

2020-12-18 00:17 UTC, taylor requested changes
duplicate

2020-12-18 00:21 UTC, williscool commented on INSTALL.md
> +<details><summary>Click here for the other curl and manual install method</summary>
how about 'alternate' instead of other?

2020-12-18 00:23 UTC, williscool commented on INSTALL.md
> +This is a brief install method and [does have requirements](#Requirements-for-source-installation) in order to compile a binary from source. To read more on source installation, see the [SOURCE-INSTA
"This is a brief" is a little unclear. how about "This is a brief summary"?

2020-12-18 02:44 UTC, agentpoyo commented on INSTALL.md
> +<details><summary>Click here for the other curl and manual install method</summary>
I was thinking that but totally mind blanked when editing it to make it a drop down.

2020-12-18 02:44 UTC, agentpoyo commented on INSTALL.md
> +This is a brief install method and [does have requirements](#Requirements-for-source-installation) in order to compile a binary from source. To read more on source installation, see the [SOURCE-INSTA
Yes, I like that after reading it out loud..

2020-12-18 02:49 UTC, agentpoyo commented on INSTALL.md
> +cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml
That's getting redundant don't you think? The bring your own CNF was going to get outlined in the link to the CNF_CONFORMANCE_YML_USAGE.md doc..  and this assumes one is following the example CNF to continue with running the next command which would be `all` or `workload` or `platform` which are just examples and reminds users they can review the USAGE.md doc for more examples.

2020-12-18 03:02 UTC, agentpoyo commented on INSTALL.md
> +cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml
Okay, I added a cnf_setup to the BYO CNF section, see if that looks okay to you. @taylor

2020-12-22 16:06 UTC, agentpoyo commented
@williscool @taylor @wavell 

Added a new POINTS.md file we can use to explain POINTS in cnf-conformance.

I ended up redoing a lot of the SOURCE INSTALL.md. It was too redundant and out of order. Tried to keep it to just source installation and getting end users a working binary or cnf-conformance suite. Keeping it short and to the point. It's an install guide, not a howto do everything to keep it more on focus.

Still need to clean up the CNF_CONFORMANCE_YML_USAGE.md I think in a friendlier format for end users. A lot of the information we had in our INSTALL I placed in this file for reference.

Please add suggestions, thoughts, adds, edits, subtractions, etc..

2020-12-22 16:08 UTC, agentpoyo commented on SOURCE_INSTALL.md
> +```
I kept this intact and moved with the other quick examples after installing example CNF in the Source-Install doc.

2020-12-22 17:06 UTC, taylor requested changes
My only suggestions are for the new changes to CNF_CONFORMANCE_YML_USAGE.md.

2020-12-22 17:08 UTC, agentpoyo commented on CNF_CONFORMANCE_YML_USAGE.md
> +  ```
Yeah, this file needs to be cleaned up. I copied and pasted remaining bits over.

2020-12-22 17:11 UTC, agentpoyo approved these changes
I think this is a good start for now.

2020-12-22 17:15 UTC, taylor approved these changes
lgtm

2020-12-22 17:15 UTC, merged