Update README-testsuite.md
cncf/cnf-conformance pull request #542
Opened 2020-12-25 20:13 UTC by sakshamgurbhele

# CNF Conformance PR Template

## Description
I have made some minor changes to this 
 added a hyphen, added a comma, and fixed the agreement mistake.

## Issues:
Refs: #541

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2020-12-26 23:01 UTC, agentpoyo requested changes

2020-12-27 06:25 UTC, sakshamgurbhele commented on README-testsuite.md
> +The CNF Conformance test suite is a tool that makes it possible to validate telco applications, aka Cloud-native Network Functions (CNFs), and the underlying Telecom platforms adherence to Cloud-nati
okay, thanks for the info. I will keep that in my mind😄

2020-12-28 17:37 UTC, wavell commented on README-testsuite.md
> +Welcome! We gladly accept contributions on new conformance tests, example CNFs, updates to documentation, enhancements, bug reports, and more.
the good ole oxford comma

2020-12-28 17:37 UTC, wavell approved these changes

2020-12-28 17:51 UTC, agentpoyo approved these changes
LGTM

2020-12-28 17:52 UTC, merged