Doc/cnf conformance yml usage #537
cncf/cnf-conformance pull request #549
Opened 2021-01-04 20:40 UTC by agentpoyo

# CNF Conformance PR Template

## Description
Documentation updates.

## Issues:
Refs: #537

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [x] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Documentation update

## Checklist:
**Documentation**
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

2021-01-04 20:47 UTC, agentpoyo reviewed
Suggestions and feedback welcome.

2021-01-04 20:47 UTC, agentpoyo commented on CNF_CONFORMANCE_YML_USAGE.md
> +The following is a basic example cnf-conformance.yml file that can be found in the cnf-conformance respository: [cnf-conformance.example.yml](https://github.com/cncf/cnf-conformance/blob/develop/cnf-
We should probably update this example with the required minimum keys/values.

2021-01-04 20:47 UTC, agentpoyo commented on CNF_CONFORMANCE_YML_USAGE.md
> +#### deployment_name
If someone wants to help add more descriptions for this and the few others that have been added since this was originally written, that would be great.

2021-01-04 20:47 UTC, agentpoyo commented on CNF_CONFORMANCE_YML_USAGE.md
> +### Creating Your Own cnf-conformance.yml
This was leftovers from the INSTALL, not sure if we need to keep or not since it kind of dives into setup below as well.

2021-01-05 22:28 UTC, taylor requested changes

2021-01-05 22:28 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +This is the path to the helm chart directory (relative to the location of the cnf-conformance.yml). This is a must and is mutually exclusive with [helm_chart](#helm_chart)
```suggestion
This is the path to the helm chart directory (relative to the location of the cnf-conformance.yml). This or   [helm_chart](#helm_chart) must be set, but only one (mutually exclusive).
```

2021-01-05 22:28 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +#### deployment_name
@williscool @denverwilliams @wavell

2021-01-05 22:28 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +The published helm chart name. Like [helm_directory](#helm_directory), this is a must and is exclusive with helm_directory.
```suggestion
The published helm chart name. Like [helm_directory](#helm_directory), this or [helm_directory](#helm_directory) must be set, but not both (mutually exclusive).
```

2021-01-05 22:28 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +This value is used to look up the CNF and determine if it's running in privileged mode (only used within the specs).  The containers in the test are now dynamically determined from the helm chart or
@agentpoyo maybe this should not be here... or there can be a **Development** section at the end with these items hidden.

2021-01-05 22:28 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +This key and value is the name of the 'container' defined in the Kubernetes pod spec of pods that are allowed to be running in privileged mode. (Optional)
```suggestion
The values of this key are the names of the 'containers' defined in the Kubernetes pod spec of pods that are allowed to be running in privileged mode. (Optional)
```

2021-01-05 22:28 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +
NOTE/TODO: This should be dynamic or it will be difficult for CNFs with a large number of containers.

(No update to docs at this time)

2021-01-05 22:28 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +### Detailed Steps
```suggestion
```

Delete it

2021-01-05 22:28 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +This will help guide you in setting up your own cnf-conformance.yml to test your own CNF.
```suggestion
A configuration file called `cnf-conformance.yml` needs to be created for each CNF you want to test (eg. `cnfs/my_ipsec_cnf/cnf-conformance.yml`).
```

2021-01-05 22:28 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +You can start by copying the example cnf-conformance.yml or copy and paste the below to get started and then filling our the appropriate values:
```suggestion
You can start by copying an example cnf-conformance.yml or copy and paste the below to get started and then filling our the appropriate values:
```

2021-01-05 22:33 UTC, agentpoyo commented on CNF_CONFORMANCE_YML_USAGE.md
> +This value is used to look up the CNF and determine if it's running in privileged mode (only used within the specs).  The containers in the test are now dynamically determined from the helm chart or
:thinking: 

I think all options for a config file should be mentioned since it's listing out all of it's 'usage' within. If we start dividing it up, it really starts to get convoluted or perhaps missed...

2021-01-05 22:35 UTC, agentpoyo commented on CNF_CONFORMANCE_YML_USAGE.md
> +
Yes, I left this as is from original doc.

2021-01-05 22:41 UTC, agentpoyo commented on CNF_CONFORMANCE_YML_USAGE.md
> +### Detailed Steps
I'll remove and cleanup the TOC and such from command line.

2021-01-06 06:06 UTC, williscool approved these changes
looks great 🚢 it!

just a few comments

2021-01-06 06:06 UTC, williscool commented on CNF_CONFORMANCE_YML_USAGE.md
> +#### helm_directory
I would just have the bit about mutual exclusivity **bolded**

2021-01-06 06:06 UTC, williscool commented on CNF_CONFORMANCE_YML_USAGE.md
> +The published helm chart name. Like [helm_directory](#helm_directory), this or [helm_directory](#helm_directory) must be set, but not both (mutually exclusive).
I would just have the bit about mutual exclusivity **bolded**

2021-01-07 18:58 UTC, taylor requested changes

2021-01-07 18:58 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +The PATH is also relative to the location of the cnf-conformance.yml. So if the cnf-conformance.yml in the directory ```charts/stable/cnf-conformance.yml``` and helm_directory is set to ```helm_direc
```suggestion
The PATH is also relative to the location of the cnf-conformance.yml. So if the cnf-conformance.yml in the directory ```cnfs/coredns/cnf-conformance.yml``` and helm_directory is set to ```helm_directory: coredns``` the test suite would expect to find the chart under [```cnfs/coredns/coredns```](https://github.com/helm/charts/tree/master/stable/coredns)
```

We refer to the directory cnfs/cnf_name repeatedly in the docs.  It is confusing to see the cnf-conformance.yml in what looks like a helm charts directory (charts/stable)

2021-01-07 18:58 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +#### deployment_name
@agentpoyo we can do a new PR in the future when @williscool @denverwilliams @wavell add descriptions

2021-01-07 18:58 UTC, taylor commented on CNF_CONFORMANCE_YML_USAGE.md
> +The following is a basic example cnf-conformance.yml file that can be found in the cnf-conformance respository: [cnf-conformance.example.yml](https://github.com/cncf/cnf-conformance/blob/develop/cnf-
@agentpoyo good idea. that can be a new PR and/or issue

2021-01-07 20:12 UTC, agentpoyo commented on CNF_CONFORMANCE_YML_USAGE.md
> +The PATH is also relative to the location of the cnf-conformance.yml. So if the cnf-conformance.yml in the directory ```charts/stable/cnf-conformance.yml``` and helm_directory is set to ```helm_direc
Yes. I left these as is from the old doc. Wasn't sure if we wanted to entertain changing, updating, coming up with a new standard generic way of explaining the structure.

2021-01-07 21:28 UTC, taylor approved these changes

2021-01-07 21:29 UTC, merged