#338 moved emoji to variables
cncf/cnf-conformance pull request #559
Opened 2021-01-09 13:37 UTC by sakshamgurbhele

# CNF Conformance PR Template

## Description
moved emoji to variables
## Issues:
Refs: #338 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2021-01-09 14:00 UTC, sakshamgurbhele reviewed
The issue is #336. sorry for that

2021-01-11 16:28 UTC, taylor requested changes

2021-01-11 16:28 UTC, taylor commented on src/tasks/litmus_setup.cr
> +        (experimentStatus != "Waiting for Job Creation" && experimentStatus != "Running" && experimentStatus != "Completed")
```suggestion
      if (experimentStatus != "Waiting for Job Creation" && experimentStatus != "Running" && experimentStatus != "Completed")
```

2021-01-11 16:28 UTC, taylor commented on src/tasks/litmus_setup.cr
> +    else
```suggestion
    else
```

2021-01-11 21:32 UTC, taylor requested changes
These else block should not have the puts on the same line.  The block is for the puts and false.

2021-01-11 21:32 UTC, taylor commented on src/tasks/litmus_setup.cr
> +    else puts "#{chaos_experiment_name} chaos test failed #{emoji_test_failed}"
```suggestion
    else 
      puts "#{chaos_experiment_name} chaos test failed #{emoji_test_failed}"
```

2021-01-11 21:33 UTC, taylor commented on src/tasks/litmus_setup.cr
> +    else puts "#{chaos_experiment_name} chaos test failed #{emoji_test_failed}"
@sakshamgurbhele You can click on "Commit suggestion"

2021-01-11 21:57 UTC, sakshamgurbhele commented
> These else block should not have the puts on the same line. The block is for the puts and false.

Ohhkkkayyy

2021-01-11 22:30 UTC, taylor approved these changes

2021-01-12 06:44 UTC, williscool approved these changes
lgtm too.

will rebase and see if that fixes

2021-01-13 21:13 UTC, taylor commented
current failing tests are caused because of lack of permissions for the CI system

2021-01-13 21:13 UTC, merged