Check kubectl version before failing immutable configmap test
cncf/cnf-conformance pull request #677
Opened 2021-03-29 17:28 UTC by sishbi

## Description
Check kubectl version before failing immutable configmap test

## Issues:
Refs: #669

## How has this been tested:
 - [X] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

Please review: @taylor @wavell

2021-04-01 06:56 UTC, williscool requested changes

2021-04-01 06:56 UTC, williscool commented on src/tasks/utils/kubectl_client.cr
> +  def self.version()
can you write a test for this please?

concerned about weird/ number string stuff

2021-04-01 06:56 UTC, williscool commented on src/tasks/workload/configuration_lifecycle.cr
> +      if k8s_ver <= "1.18"
does this work with a string / number?

2021-04-01 15:12 UTC, taylor commented on src/tasks/workload/configuration_lifecycle.cr
> +      if k8s_ver <= "1.18"
https://github.com/crystal-lang/crystal/blob/master/src/semantic_version.cr

2021-04-07 11:10 UTC, sishbi commented on src/tasks/utils/kubectl_client.cr
> +  def self.version()
Does using semantic version library resolve this concern?

2021-04-07 11:11 UTC, sishbi commented on src/tasks/workload/configuration_lifecycle.cr
> +      if k8s_ver <= "1.18"
I have implemented the check using semantic_version library

2021-04-07 22:38 UTC, merged