Fix for rolling_version_change where the version is an integer
cncf/cnf-conformance pull request #683
Opened 2021-03-31 12:21 UTC by sishbi

## Description
when converting a hash value to string try to convert integer to string if value isn't a string

## Issues:
Refs: #682 

## How has this been tested:
 - [X] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

Please review:
@taylor @wavell @lixuna

2021-04-01 06:32 UTC, williscool requested changes

2021-04-01 06:32 UTC, williscool commented on src/tasks/utils/utils.cr
> +  if ENV.has_key?("LOGLEVEL")
@sishbi can you remote the whitespace changes please?

2021-04-01 06:32 UTC, williscool commented on src/tasks/utils/utils.cr
> +  "#{totem_config[key_name]? && (totem_config[key_name].as_s? || totem_config[key_name].as_i?)}"
@sishbi can you add a comment with format of version number this fixes?

2021-04-07 10:17 UTC, sishbi commented on src/tasks/utils/utils.cr
> +  if ENV.has_key?("LOGLEVEL")
As discussed in the meeting, this is a side-effect of my IDE fixing trailing whitespace issues.
I have modified the settings to only fix lines that are modified so hopefully that will resolve this going forward.

2021-04-07 10:27 UTC, sishbi commented on src/tasks/utils/utils.cr
> +  "#{totem_config[key_name]? && (totem_config[key_name].as_s? || totem_config[key_name].as_i?)}"
Comment added

2021-04-07 23:19 UTC, merged